# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('center_type', models.CharField(max_length=15)),
                ('cnpj', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento_data', models.DateField()),
                ('medicamento_nome', models.CharField(max_length=45)),
                ('medicamento_dosagem', models.CharField(max_length=45)),
                ('medicamento_fabricante', models.CharField(max_length=45)),
                ('medicamento_quantidade', models.DecimalField(decimal_places=0, max_digits=5)),
                ('medicamento_preco', models.DecimalField(decimal_places=2, max_digits=2)),
                ('medicamento_endereco', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='n_User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('utype', models.CharField(blank=True, max_length=3, null=True)),
                ('dj_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_cpf', models.CharField(max_length=11)),
                ('patient_birthday', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proc.n_User')),
            ],
        ),
    ]
