# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0002_auto_20170614_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenterOk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_nome', models.CharField(max_length=60)),
                ('centro_tipo', models.CharField(max_length=30)),
                ('centro_endereco', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proc.n_User')),
            ],
        ),
        migrations.DeleteModel(
            name='HealthCenter',
        ),
    ]
